- name: Update apt
  apt:
    update_cache: yes

- name: Install Docker & Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Start Docker manually
  shell: dockerd &
  async: 10
  poll: 0
  ignore_errors: yes

- name: Add user to docker group
  user:
    name: root
    groups: docker
    append: yes

- name: Allow SSH only
  shell: |
    ufw allow 22/tcp
    ufw --force enable
  ignore_errors: yes

- name: Enable firewall
  shell: ufw status
  ignore_errors: yes
